services:
  api-gw:
    image: ${DOCKER_USERNAME}/katisha-api-gw:${IMAGE_TAG:-latest}
    container_name: api-gw
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      CONFIG_REPO_URL: ${CONFIG_REPO_URL}
      CONFIG_REPO_TOKEN: ${CONFIG_REPO_TOKEN}
      CONFIG_POLL_INTERVAL_MS: ${CONFIG_POLL_INTERVAL_MS}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
    networks:
      - katisha-net

networks:
  katisha-net:
    external: true
